### ISSUE TITLE
Can't Activate Plug-in

### ISSUE THREAD

**Issue by PloyPanmaneeCNC** [iamapinan/PDPA-Consent#12]
After install when try to activate this show up

`Parse error: syntax error, unexpected ')' in /var/www/html/wp-content/plugins/PDPA-Consent-1.0.1/admin.php on line 93`

Image: https://imgur.com/a/xxJ7uN2

**Comment by iamapinan** [comment]
Please update to [v1.0.2](https://github.com/iamapinan/PDPA-Consent/releases/tag/v1.0.2)  or latest.

**Comment by PloyPanmaneeCNC** [comment]
It's works thanks
