### ISSUE TITLE
Consent buttons don't work correctly

### ISSUE THREAD

**Issue by d4n5h** [iamapinan/PDPA-Consent#25]
The problem is that if i click the "allow" button and the refresh the page then the consent popup will appear again, and then if i click on the "allow" button again then the popup/modal won't close.

The issue persists both in mobile and desktop browsers (every browser).
![ezgif-6-d36e3d970f4b.gif](https://user-images.githubusercontent.com/1638614/88777951-0f578800-d1b2-11ea-9d1a-6802c668df41.gif)

**Comment by iamapinan** [comment]
Please update to v.1.1.1

**Comment by d4n5h** [comment]
@iamapinan 
I'm using the latest version

**Comment by d4n5h** [comment]
@iamapinan Hi, Any updates regarding this issue?

**Comment by iamapinan** [comment]
> @iamapinan Hi, Any updates regarding this issue?
can i check your website?

**Comment by iamapinan** [comment]
@d4n5h let me know your website URL with plugin install and activated.

**Comment by d4n5h** [comment]
@iamapinan https://www.rvconnex.com

**Comment by iamapinan** [comment]
@d4n5h After test with myself.
Your website is working correctly.
Some case the issue depends on your web browser or devices. 
Please, re testing again with another device or computer. 

---
[Imgur](https://imgur.com/HXY4smH)

Thank you.

**Comment by d4n5h** [comment]
@iamapinan I tried in multiple devices and multiple browsers. Try again using incognito mode.

**Comment by iamapinan** [comment]
@d4n5h I test again and record video for you.
please check this link https://drive.google.com/file/d/155i0M8GoGO10Cr5WkkJxAmyyh7wddBXF/view?usp=sharing

**If you still can not get it work on your device please provide more info about your enviroment such as device os, web browser and web browser setting for current website.**

**Comment by iamapinan** [comment]
Or you just clear cache on your web browser and test again

**Comment by d4n5h** [comment]
@iamapinan I'm testing in "incognito" so cache isn't the issue. And as I said, I it's happening in every browser on every device.
Please click on "allow" and then refresh the page. You will see that the consent form will still appear even though you already clicked on "allow" and in the seco d time you'll click on "allow" then it won't close the consent popup.

**Comment by iamapinan** [comment]
> @d4n5h I test again and record video for you.
> please check this link https://drive.google.com/file/d/155i0M8GoGO10Cr5WkkJxAmyyh7wddBXF/view?usp=sharing
> 
> **If you still can not get it work on your device please provide more info about your enviroment such as device os, web browser and web browser setting for current website.**

Like this please provide more info and screenshot.
I have tested on my mobile device and other computer it working correcly.

**Comment by d4n5h** [comment]
@iamapinan in the screen capture video you didn't refresh after clicking "allow".
So you didn't check it correctly and please do it in mobile browser because  on desktop sometimes it will work and sometimes it doesn't.
