### ISSUE TITLE
Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by sorawitw** [iamapinan/PDPA-Consent#26]
**Describe the bug**
When I installed your plugin and activate to use it. It didn't appear consent notification and nothing to happen.

**To Reproduce**
1. Go to 'my website'
3. Consent notification is not working
4. See errors on web browser console is following:

Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.<anonymous> (pdpa-consent.js?ver=1.1.1:8)

**Expected behavior**
Please help, Thank you.

**Test on:**
 - Plugin version: 1.1.1
 - Browser: Chrome
 - PHP version: 5.6.20
 - Wordpress Version 5.4.2

**My website URL**:
https://mb.mahidol.ac.th

**Comment by iamapinan** [comment]
@sorawitw Because your theme does't support wp_body_open hook this come with WordPress 5.2 or later. 
However please check theme support for update to support wp_body_open hook or just add 
`add_action('wp_body_open')` under `<body>` tag of your theme.

**Comment by sorawitw** [comment]
@iamapinan Thank you krub.
